name: Build and Deploy Laravel App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, ctype, json, bcmath, gd, fileinfo
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set Up Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Cache Config & Optimize App
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate --force

      - name: Upload Laravel Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: laravel-build
          path: ./

  deploy:
    name: Deploy to AWS Lightsail
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: laravel-build
          path: /home/ubuntu/laravel-app

      - name: Deploy Laravel App to AWS Lightsail
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LIGHTSAIL_IP: "13.43.41.67"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy files to Lightsail instance
          rsync -avz --delete -e "ssh -i private_key.pem" /home/ubuntu/laravel-app/ ubuntu@$LIGHTSAIL_IP:/var/www/html

          # SSH into the server and deploy
          ssh -i private_key.pem ubuntu@$LIGHTSAIL_IP << 'EOF'
            cd /var/www/html

            # Set permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Install dependencies on server
            composer install --no-dev --optimize-autoloader

            # Set up environment
            cp .env.example .env
            php artisan key:generate

            # Run migrations
            php artisan migrate --force

            # Clear and cache
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart Apache & Supervisor for workers
            sudo systemctl restart apache2
            sudo supervisorctl restart all
          EOF
