name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, exif, pcntl, bcmath, gd, pdo_pgsql

    - name: Install PostgreSQL PHP Extension
      run: |
        sudo apt-get update
        sudo apt-get install -y php8.2-pgsql --fix-missing

    - name: Cache Composer Dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: composer-

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache NPM Dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-

    - name: Install NPM Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: public/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: public/build

    - name: Run Database Migrations
      run: php artisan migrate --force

    - name: Restart Laravel Queue Worker
      run: pm2 restart laravel-worker || pm2 start php --name "laravel-worker" -- artisan queue:work --tries=3 --daemon

    - name: Deployment Completed
      run: echo "Deployment completed successfully!"
