name: Build and Deploy Laravel App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Cache Config and Routes
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Archive Build Artifacts
        run: tar -cvf laravel-build.tar.gz . 

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-build
          path: laravel-build.tar.gz

  deploy:
    name: Deploy to AWS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: laravel-build
          path: .

      - name: Prepare SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to AWS Lightsail using rsync
        env:
          LIGHTSAIL_IP: "51.24.31.0"
        run: |
          # Upload the repository to Lightsail using rsync (Bypassing Host Key Verification)
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem" --exclude 'vendor' --exclude '.git' --exclude 'node_modules' ./ ubuntu@$LIGHTSAIL_IP:/home/ubuntu/laravel

          # Connect to Lightsail and deploy
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key.pem ubuntu@$LIGHTSAIL_IP << 'EOF'
            # Ensure necessary directories exist and have correct permissions
            sudo mkdir -p /var/www/html
            sudo chown -R ubuntu:ubuntu /var/www

            cd /home/ubuntu/laravel

            # Install Composer dependencies (ensure composer is available)
            if ! command -v composer &> /dev/null; then
              echo "Composer not found. Installing Composer..."
              curl -sS https://getcomposer.org/installer | php
              sudo mv composer.phar /usr/local/bin/composer
            fi

            # Install dependencies with Composer
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            # Run migrations and link storage
            php artisan migrate --force
            php artisan storage:link

            # Set correct permissions for Laravel directories
            sudo mkdir -p storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing PM2..."
              sudo npm install -g pm2
            fi

            # Start the Laravel application using PM2
            pm2 start php artisan serve --name "laravel-app" -- --host=0.0.0.0 --port=8000

            # Save PM2 process list
            pm2 save

            # Restart Apache or Nginx (check for which web server is installed)
            if systemctl list-units --type=service | grep -q apache2; then
              sudo systemctl restart apache2
            elif systemctl list-units --type=service | grep -q nginx; then
              sudo systemctl restart nginx
            else
              echo "Neither Apache nor Nginx is installed."
            fi
          EOF
