name: Build and Deploy Laravel App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Cache Config and Routes
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Archive Build Artifacts
        run: tar -cvf laravel-build.tar.gz . 

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-build
          path: laravel-build.tar.gz

  deploy:
    name: Deploy to AWS Lightsail
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: laravel-build
          path: .

      - name: Prepare SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to AWS Lightsail
        env:
          LIGHTSAIL_IP: "51.24.31.0"
        run: |
          # Upload build to Lightsail (Bypassing Host Key Verification)
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -i private_key.pem laravel-build.tar.gz ubuntu@$LIGHTSAIL_IP:/home/ubuntu

          # Connect and deploy
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -i private_key.pem ubuntu@$LIGHTSAIL_IP << 'EOF'
            cd /home/ubuntu
            tar -xvf laravel-build.tar.gz -C /var/www/html
            cd /var/www/html
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan storage:link
            chmod -R 775 storage bootstrap/cache
            sudo systemctl restart apache2
          EOF
